#ifndef DEFS_H
#define DEFS_H

#define WINDOW_TITLE "AWAKE"
enum resolution {
	SCREEN_WIDTH = 1280,
	SCREEN_HEIGHT = 960
};

#define IMAGE_FLAGS IMG_INIT_PNG
enum delay {
	DELAY_ONE_FRAME = 16,
	DELAY_TWO_FRAMES = 32,
	DELAY_THREE_FRAMES = 48,
	DELAY_FOUR_FRAMES = 64
};

#endif
